spring:
  data:
    rest:
      defaultMediaType: application/json
      default-media-type: application/json
  config:
    import:
      - "aws-secretsmanager:rds!db-06515a50-a643-4063-8a71-6cf8f0ae1f24"
      - "optional:aws-secretsmanager:dev/creds/spotify"
  application:
    name: jukeboxd-api
  jmx:
    enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: log
  flyway:
    enabled: false
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      pool-name: pool-starter
      url: jdbc-secretsmanager:postgresql://jukeboxddb.cqu68g53egxs.us-east-2.rds.amazonaws.com:5432/postgres
      username: rds!db-06515a50-a643-4063-8a71-6cf8f0ae1f24
      password: rds!db-06515a50-a643-4063-8a71-6cf8f0ae1f24
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/
          jwk-set-uri: http://localhost:8083/auth/certs

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  cache:
    disabled: true

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /v1

spotify:
  url:
    token: https://accounts.spotify.com/api/token
    api: https://api.spotify.com/v1/