spring:
  data:
    rest:
      defaultMediaType: application/json
      default-media-type: application/json
  application:
    name: jukeboxd-api
  jmx:
    enabled: true
  main:
    allow-bean-definition-overriding: true
    banner-mode: log

  flyway:
    enabled: true
    locations: classpath:/db/migration

  datasource:
    database-platform: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jukeboxd_db
    username: usr_admin
    password: rds!db-06515a50-a643-4063-8a71-6cf8f0ae1f24
    hikari:
      maximum-pool-size: 5
      connection-timeout: 5000
      pool-name: pool-starter
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/
          jwk-set-uri: http://localhost:8083/auth/certs

management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
  cache:
    disabled: true

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /v1

spotify:
  url:
    token: https://accounts.spotify.com/api/token
    api: https://api.spotify.com/v1/
  secret: fdad6a72f10b413d8a05b2206b1f265d
  id: 4d0a47e081ad43bf8b9a5ad9a420f989